Update data preparing script for upcoming changes.
* move indexes and pieces to the root of data directory.
* move all contents into contents directory to avoid directory name collision.
+ now use empty argument for generate data for all namespace.
+ message for skip duplicate resources.
+ add directory index for resource indexes.
* filter options passed to ContentFile.

diff --git a/bin/generate b/bin/generate
--- a/bin/generate
+++ b/bin/generate
@@ -2,21 +2,38 @@
 
 set -e
 
-# set default key
-[ -z "$1" ] && KEY=bcdn
+# handle keys
+export DIR_ROOT="$(pwd)"
+
+if [ -z "$1" ]; then
+    DIR_FILES="${DIR_ROOT}/files"
+    [ -d "$DIR_FILES" ] \
+        || { echo "Error: path ${DIR_FILES} is not a directory!" >/dev/stderr
+             exit 1; }
+
+    echo "Generating for all keys..."
+    ls "$DIR_FILES" | xargs -d'\n' -n1 "$0"
+
+    exit 0
+else
+    KEY="$1"
+    DIR_FILES="${DIR_ROOT}/files/$KEY"
+    [ -d "$DIR_FILES" ] \
+        || { echo "Error: path ${DIR_FILES} is not a directory!" >/dev/stderr
+             exit 1; }
+fi
 
 # setup
 TIMESTAMP="$(date +%s)"
-DIR_ROOT="$(pwd)"
-DIR_FILES="${DIR_ROOT}/files/$KEY"
-DIR_DATA="${DIR_ROOT}/data/$KEY"
-DIR_TMPDATA="${DIR_DATA}-tmp_$TIMESTAMP"
+DIR_DATA="${DIR_ROOT}/data"
+DIR_CONTENTS="${DIR_DATA}/contents/$KEY"
+DIR_CONTENTS_TMP="${DIR_CONTENTS}-tmp_$TIMESTAMP"
 HASH_TOOL=sha256sum
 CHUNK_SIZE=256K
 
 # cleanup on error or exit
 cleanup() {
-    rm -rf "$DIR_TMPDATA"
+    rm -rf "$DIR_CONTENTS_TMP"
 }
 trap cleanup INT TERM ERR EXIT
 
@@ -32,13 +49,12 @@ check split
 check find
 
 # prepare directories
-mkdir -p "$DIR_FILES"
-mkdir -p "$DIR_TMPDATA"
-mkdir -p "$DIR_TMPDATA/indexes"
-mkdir -p "$DIR_TMPDATA/pieces"
+mkdir -p "$DIR_CONTENTS_TMP"
 
 # generate data directory
-echo "generating..."
+echo
+echo
+echo "Generating for key=${KEY}..."
 cd "$DIR_FILES"
 N_FILES="$(find -type f | wc -l)"
 find -type f | while read FILE; do
@@ -48,19 +64,25 @@ find -type f | while read FILE; do
 
     # hash and build entry
     echo "[${I_FILES}/${N_FILES}] ${FILE}: hashing..."
-    HASH="$("$HASH_TOOL" "$FILE" | cut -sd' ' -f-1)"
-    ENTRY="$(stat -c'%n %s' "$FILE") $HASH"
+    RES_HASH="$("$HASH_TOOL" "$FILE" | cut -sd' ' -f-1)"
+    ENTRY="$(stat -c'%n %s' "$FILE") $RES_HASH"
 
     # add to contents
     echo "[${I_FILES}/${N_FILES}] ${FILE}: add to contents"
-    echo "/$ENTRY" >> "${DIR_TMPDATA}/contents"
+    echo "/$ENTRY" >> "${DIR_CONTENTS_TMP}/contents"
 
     # check duplicate
-    [ -f "${DIR_TMPDATA}/indexes/${HASH}" ] && continue
+    DIR_INDEX="$DIR_DATA/indexes/$(echo "$RES_HASH" | cut -c-2)"
+    mkdir -p "$DIR_INDEX"
+    FILE_INDEX="${DIR_INDEX}/${RES_HASH}"
+    [ -f "${FILE_INDEX}" ] && {
+        echo "[${I_FILES}/${N_FILES}] ${FILE}: duplicate file found, skip."
+        continue; }
 
     # split file
-    mkdir "${DIR_TMPDATA}/${HASH}"
-    cd "${DIR_TMPDATA}/${HASH}"
+    DIR_SPLIT_TMP="${DIR_DATA}/split-${RES_HASH}"
+    mkdir -p "$DIR_SPLIT_TMP"
+    cd "$DIR_SPLIT_TMP"
     echo "[${I_FILES}/${N_FILES}] ${FILE}: splitting..."
     split -b "$CHUNK_SIZE" "${DIR_FILES}/${FILE}"
 
@@ -72,23 +94,25 @@ find -type f | while read FILE; do
         PC_HASH="$("$HASH_TOOL" "$PIECE" | cut -sd' ' -f-1)"
         echo "[${I_FILES}/${N_FILES}-${I_PIECES}/${N_PIECES}]" \
              "processing ${PC_HASH}..."
-        echo "$PC_HASH" >> "${DIR_TMPDATA}/indexes/${HASH}"
+        echo "$PC_HASH" >> "${FILE_INDEX}"
 
-        DIR_DIST="$DIR_TMPDATA/pieces/$(echo "$PC_HASH" | cut -c-2)"
-        mkdir -p "$DIR_DIST"
+        DIR_PIECE="$DIR_DATA/pieces/$(echo "$PC_HASH" | cut -c-2)"
+        mkdir -p "$DIR_PIECE"
 
-        mv "$PIECE" "${DIR_DIST}/${PC_HASH}"
+        mv "$PIECE" "${DIR_PIECE}/${PC_HASH}"
     done
 
-    # remove temporary directory for storing pieces
+    # remove temporary directory for splitting files
+    rm -rf "$DIR_SPLIT_TMP"
+
+    # be prepared for the next file
     cd "$DIR_FILES"
-    rm -rf "${DIR_TMPDATA}/${HASH}"
 done
 
 # update data directory
-rm -rf "$DIR_DATA"
-mv "$DIR_TMPDATA" "$DIR_DATA"
-echo "$TIMESTAMP" > "${DIR_DATA}/timestamp"
+rm -rf "$DIR_CONTENTS"
+mv "$DIR_CONTENTS_TMP" "$DIR_CONTENTS"
+echo "$TIMESTAMP" > "${DIR_CONTENTS}/timestamp"
 
 # TODO: notify server for the update
 
